Traceback (most recent call last):
  File "/home/db_user/datacup-challenge-esi-dev/RequeteAPI/Importregulier.py", line 2, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  File "/home/db_user/datacup-challenge-esi-dev/RequeteAPI/Importregulier.py", line 2, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  File "/home/db_user/datacup-challenge-esi-dev/RequeteAPI/Importregulier.py", line 2, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  File "/home/db_user/datacup-challenge-esi-dev/RequeteAPI/Importregulier.py", line 2, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
Date maximale : 2024-11-22 06:00:00
Aucune donnée supplémentaire trouvée.
